### ISSUE TITLE
Sort function no longer works after lebab

### ISSUE THREAD

**Issue by soniCaH** [lebab/lebab#285] opened 2019-01-17 08:23 UTC
When having an (anonymous) sort function comparing the same property of "a" with "b", the function gets invalid after running lebab, since it removes the context of a and b completely.

Example:

```
this.data.sort((a, b) => a.dateTime - b.dateTime);
```

gets rewritten to

```
this.data.sort(({dateTime}, {dateTime}) => dateTime - dateTime);
```

**Comment by soniCaH** [comment] 2019-01-17 08:44
Same happens for other types of functions using the same property of two different objects, like this distanceBetween function:

```
	function distanceBetween( a, b ) {

		var dx = a.x - b.x,
			dy = a.y - b.y;

		return Math.sqrt( dx*dx + dy*dy );

	}
```

becomes
```
    function distanceBetween({x, y}, {x, y}) {
        const dx = x - x;
        const dy = y - y;

        return Math.sqrt( dx*dx + dy*dy );
    }
```

**Comment by nene** [comment] 2019-01-17 13:39
Yeah. That's a known issue.

Closing this as a duplicate of https://github.com/lebab/lebab/issues/200

Thanks for reporting though and bringing it up again.

**Closed by nene** 2019-01-17 13:39 UTC
