### ISSUE TITLE
Execute all safe transforms at once

### ISSUE THREAD

**Issue by bennyn** [lebab/lebab#223] opened 2017-03-15 11:32 UTC
At the moment you need to list up all the transformations you want to make, like: 

```bash
lebab --replace src/main/js/ -t arrow,for-of,for-each,arg-rest,arg-spread,obj-method,obj-shorthand,no-strict,exponent,multi-var
```

It would be nice if I could run all safe transformations at once with a shortcut like:

```bash
lebab --replace src/main/js/ --transform all-safe
```

Do you plan to add something like this?

**Comment by nene** [comment] 2017-03-15 13:59
This is by design, as executing all the transforms (even the safe ones) in one go is not the recommended practice. Even when the transform is marked as safe, I don't give 100% guarantee that it won't break your code and even most of the safe transforms have known shortcomings. You really shouldn't apply these transforms blindly, and even if you do I'd recommend doing a separate commit after applying each transform, so that when you later discover a regression, you can backtrack it to a particular transform that broke things.

Lebab used to actually execute all transforms by default in 1.x version. Simply telling in documentation that executing all transforms at once is not recommended didn't stop people doing this and occasionally shooting themselves in the foot. So I explicitly made it harder to use Lebab in this way.

**Closed** 2017-04-25 09:31 UTC
