### ISSUE TITLE
ignore var redeclare

### ISSUE THREAD

**Issue by graingert** [lebab/lebab#143] opened 2016-07-04 11:17 UTC
redeclares should be ignored:

``` js
function foo (){
  var a = 3;
  for (i in x) {
    var a = 7;
  }
}
```

is the same as:

``` js
function foo (){
  var a = 3;
  for (i in x) {
    a = 7;
  }
}
```

so both should become:

``` js
function foo (){
  let a = 3;
  for (i in x) {
    a = 7;
  }
}
```

**Comment by nene** [comment] 2016-07-07 12:50
Yeah. Actually the current implementation tries to ignore the redeclared variables, but the result is not pretty. Probably better to convert the redeclares to simple assignments. This should actually simplify the transformation code.

**Comment by nene** [comment] 2018-09-12 15:29
The tricky case in here is this scenario:

```js
function foo() {
  if (true) {
    var x = 1;
  } else {
    var x = 2;
  }
  return x;
}
```

We can't just blindly convert the first `var` to `let` and the other one to assignment - the variable would only be visible within the first block. We would need to move the let declaration out of the if statement entirely, like so:

```js
function foo() {
  let x;
  if (true) {
    x = 1;
  } else {
    x = 2;
  }
  return x;
}
```

That's a pretty substantial stylistic change though. You might or might not like the outcome.

I think it's usually better to reformat such code manually.

**Comment by graingert** [comment] 2018-09-12 16:00
You should always hoist that let manually

**Comment by Itee** [comment] 2018-09-12 18:49
In my opinion, Re-declare a variable should issue a warning. You can not know the intent of the programmer. Maybe there is the key word var in too much, or maybe the name of the variable is incorrect.

**Comment by graingert** [comment] 2018-09-12 19:03
Sure it should issue the warning, but the syntactical hoisting should be available as an option. I want a tool that can eliminate `var` from a codebase

**Comment by nene** [comment] 2018-09-12 20:19
One should also consider a very similar case:

```js
function foo() {
  if (true) {
    var x = 1;
    return x;
  } else {
    var x = 2;
    return x;
  }
}
```

Here the `var`-s can be transformed to two `const` declarations. Telling the difference though requires a fair bit of static analyzing. And even then, I'd say you're still better off investigating each such case manually.

BTW, the warning should be already there.

For now I'm not really planning to work on this. The `let` transform is already the most complex of all of them, and there are actual bugs still in there.

**Comment by nene** [comment] 2023-03-12 19:37
Closing this as the current behavior is as intended.

- it's really tricky to safely transform this code
- the resulting code might not look any better
- a warning gets printed, so the developer can manually analyze their code and change it manually.

**Closed by nene** 2023-03-12 19:37 UTC
Labels: enhancement
